// Code generated by stanc v2.38.0
#include <stan/model/model_header.hpp>
namespace crown_ratio_change_fixed_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 56> locations_array__ =
  {" (found before start of program)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 33, column 2 to column 10)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 2 to column 10)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 11 to column 19)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 20 to column 28)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 29 to column 37)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 38 to column 46)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 34, column 47 to column 55)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 35, column 2 to column 24)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 36, column 2 to column 22)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 39, column 2 to column 28)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 62, column 2 to column 24)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 63, column 2 to line 67, column 33)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 41, column 7 to column 44)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 40, column 19 to column 44)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 40, column 2 to line 41, column 44)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 68, column 21 to column 81)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 68, column 2 to column 81)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 44, column 2 to column 26)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 45, column 2 to column 25)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 46, column 2 to column 26)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 47, column 2 to column 26)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 48, column 2 to column 26)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 49, column 2 to column 25)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 50, column 2 to column 25)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 51, column 2 to column 25)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 52, column 2 to column 25)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 54, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 54, column 2 to line 58, column 33)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 59, column 2 to column 33)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 17, column 2 to column 21)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 18, column 2 to column 20)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 19, column 2 to column 23)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 21, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 21, column 2 to column 27)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 22, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 22, column 2 to column 20)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 23, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 23, column 2 to column 23)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 24, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 24, column 2 to column 26)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 25, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 25, column 2 to column 27)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 26, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 26, column 2 to column 24)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 27, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 27, column 2 to column 23)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 29, column 8 to column 13)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 29, column 2 to column 47)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 30, column 9 to column 13)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 30, column 15 to column 40)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 30, column 2 to column 44)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 35, column 9 to column 16)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 39, column 9 to column 13)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 62, column 9 to column 14)",
  " (in '/users/PUOM0008/crsfaaron/fvs-conus/stan/crown_ratio_change_fixed.stan', line 63, column 9 to column 14)"};
class crown_ratio_change_fixed_model final : public model_base_crtp<crown_ratio_change_fixed_model> {
 private:
  int N_obs;
  int N_sp;
  int P_trait;
  Eigen::Matrix<double,-1,1> delta_CR_a_data__;
  Eigen::Matrix<double,-1,1> dbh_data__;
  Eigen::Matrix<double,-1,1> dbh_sq_data__;
  Eigen::Matrix<double,-1,1> ba_metric_data__;
  Eigen::Matrix<double,-1,1> bal_metric_data__;
  Eigen::Matrix<double,-1,1> cr_init_data__;
  Eigen::Matrix<double,-1,1> ln_csi_data__;
  std::vector<int> sp_idx;
  Eigen::Matrix<double,-1,-1> W_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> delta_CR_a{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> dbh{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> dbh_sq{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> ba_metric{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> bal_metric{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> cr_init{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> ln_csi{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
 public:
  ~crown_ratio_change_fixed_model() {}
  crown_ratio_change_fixed_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "crown_ratio_change_fixed_model_namespace::crown_ratio_change_fixed_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 30;
      context__.validate_dims("data initialization", "N_obs", "int",
        std::vector<size_t>{});
      N_obs = std::numeric_limits<int>::min();
      current_statement__ = 30;
      N_obs = context__.vals_i("N_obs")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "N_obs", N_obs, 1);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "N_sp", "int",
        std::vector<size_t>{});
      N_sp = std::numeric_limits<int>::min();
      current_statement__ = 31;
      N_sp = context__.vals_i("N_sp")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "N_sp", N_sp, 1);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "P_trait", "int",
        std::vector<size_t>{});
      P_trait = std::numeric_limits<int>::min();
      current_statement__ = 32;
      P_trait = context__.vals_i("P_trait")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "P_trait", P_trait, 0);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("delta_CR_a", "N_obs", N_obs);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "delta_CR_a", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      delta_CR_a_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                            std::numeric_limits<double>::quiet_NaN());
      new (&delta_CR_a)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(delta_CR_a_data__.data(),
        N_obs);
      {
        std::vector<local_scalar_t__> delta_CR_a_flat__;
        current_statement__ = 34;
        delta_CR_a_flat__ = context__.vals_r("delta_CR_a");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(delta_CR_a, delta_CR_a_flat__[(pos__ - 1)],
            "assigning variable delta_CR_a", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 35;
      stan::math::validate_non_negative_index("dbh", "N_obs", N_obs);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "dbh", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      dbh_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                     std::numeric_limits<double>::quiet_NaN());
      new (&dbh) Eigen::Map<Eigen::Matrix<double,-1,1>>(dbh_data__.data(),
        N_obs);
      {
        std::vector<local_scalar_t__> dbh_flat__;
        current_statement__ = 36;
        dbh_flat__ = context__.vals_r("dbh");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(dbh, dbh_flat__[(pos__ - 1)],
            "assigning variable dbh", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      stan::math::validate_non_negative_index("dbh_sq", "N_obs", N_obs);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "dbh_sq", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      dbh_sq_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                        std::numeric_limits<double>::quiet_NaN());
      new (&dbh_sq)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(dbh_sq_data__.data(), N_obs);
      {
        std::vector<local_scalar_t__> dbh_sq_flat__;
        current_statement__ = 38;
        dbh_sq_flat__ = context__.vals_r("dbh_sq");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(dbh_sq, dbh_sq_flat__[(pos__ - 1)],
            "assigning variable dbh_sq", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 39;
      stan::math::validate_non_negative_index("ba_metric", "N_obs", N_obs);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "ba_metric", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      ba_metric_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                           std::numeric_limits<double>::quiet_NaN());
      new (&ba_metric)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(ba_metric_data__.data(),
        N_obs);
      {
        std::vector<local_scalar_t__> ba_metric_flat__;
        current_statement__ = 40;
        ba_metric_flat__ = context__.vals_r("ba_metric");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(ba_metric, ba_metric_flat__[(pos__ - 1)],
            "assigning variable ba_metric", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      stan::math::validate_non_negative_index("bal_metric", "N_obs", N_obs);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "bal_metric", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      bal_metric_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                            std::numeric_limits<double>::quiet_NaN());
      new (&bal_metric)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(bal_metric_data__.data(),
        N_obs);
      {
        std::vector<local_scalar_t__> bal_metric_flat__;
        current_statement__ = 42;
        bal_metric_flat__ = context__.vals_r("bal_metric");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(bal_metric, bal_metric_flat__[(pos__ - 1)],
            "assigning variable bal_metric", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 43;
      stan::math::validate_non_negative_index("cr_init", "N_obs", N_obs);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "cr_init", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      cr_init_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                         std::numeric_limits<double>::quiet_NaN());
      new (&cr_init)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(cr_init_data__.data(), N_obs);
      {
        std::vector<local_scalar_t__> cr_init_flat__;
        current_statement__ = 44;
        cr_init_flat__ = context__.vals_r("cr_init");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(cr_init, cr_init_flat__[(pos__ - 1)],
            "assigning variable cr_init", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("ln_csi", "N_obs", N_obs);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "ln_csi", "double",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      ln_csi_data__ = Eigen::Matrix<double,-1,1>::Constant(N_obs,
                        std::numeric_limits<double>::quiet_NaN());
      new (&ln_csi)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(ln_csi_data__.data(), N_obs);
      {
        std::vector<local_scalar_t__> ln_csi_flat__;
        current_statement__ = 46;
        ln_csi_flat__ = context__.vals_r("ln_csi");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          stan::model::assign(ln_csi, ln_csi_flat__[(pos__ - 1)],
            "assigning variable ln_csi", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 47;
      stan::math::validate_non_negative_index("sp_idx", "N_obs", N_obs);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "sp_idx", "int",
        std::vector<size_t>{static_cast<size_t>(N_obs)});
      sp_idx = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      current_statement__ = 48;
      sp_idx = context__.vals_i("sp_idx");
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "sp_idx", sp_idx, 1);
      current_statement__ = 48;
      stan::math::check_less_or_equal(function__, "sp_idx", sp_idx, N_sp);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("W", "N_sp", N_sp);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("W",
        "P_trait > 0 ? P_trait : 1",
        (stan::math::logical_gt(P_trait, 0) ? P_trait : 1));
      current_statement__ = 51;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(N_sp),
          static_cast<size_t>(
            (stan::math::logical_gt(P_trait, 0) ? P_trait : 1))});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant(N_sp,
                   (stan::math::logical_gt(P_trait, 0) ? P_trait : 1),
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), N_sp,
        (stan::math::logical_gt(P_trait, 0) ? P_trait : 1));
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 51;
        W_flat__ = context__.vals_r("W");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <=
             (stan::math::logical_gt(P_trait, 0) ? P_trait : 1); ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N_sp; ++sym2__) {
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 52;
      stan::math::validate_non_negative_index("gamma", "P_trait", P_trait);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("trait_effect", "N_sp", N_sp);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("log_lik", "N_obs", N_obs);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("mu_pred", "N_obs", N_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + P_trait + 1;
  }
  inline std::string model_name() const final {
    return "crown_ratio_change_fixed_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.38.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "crown_ratio_change_fixed_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto b0 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto b1 = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto b2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto b3 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto b4 = in__.template read<local_scalar_t__>();
      current_statement__ = 6;
      auto b5 = in__.template read<local_scalar_t__>();
      current_statement__ = 7;
      auto b6 = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto gamma =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P_trait);
      current_statement__ = 9;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> trait_effect =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_sp, DUMMY_VAR__);
      current_statement__ = 15;
      if (stan::math::logical_gt(P_trait, 0)) {
        current_statement__ = 14;
        stan::model::assign(trait_effect, stan::math::multiply(W, gamma),
          "assigning variable trait_effect");
      } else {
        current_statement__ = 13;
        stan::model::assign(trait_effect, stan::math::rep_vector(0.0, N_sp),
          "assigning variable trait_effect");
      }
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b0, 0.0, 0.25));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b1, 0.0, 0.1));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b2, 0.0, 0.01));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b3, 0.0, 0.05));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b4, 0.0, 0.05));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b5, -(0.1), 0.5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b6, 0.0, 0.5));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(gamma,
                         static_cast<double>(0), 0.5));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma,
                         static_cast<double>(0), 0.5));
        current_statement__ = 27;
        stan::math::validate_non_negative_index("mu", "N_obs", N_obs);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_obs, DUMMY_VAR__);
        current_statement__ = 28;
        stan::model::assign(mu,
          stan::math::add(
            stan::math::add(
              stan::math::add(
                stan::math::add(
                  stan::math::add(
                    stan::math::add(
                      stan::math::add(b0,
                        stan::model::rvalue(trait_effect, "trait_effect",
                          stan::model::index_multi(sp_idx))),
                      stan::math::multiply(b1, dbh)),
                    stan::math::multiply(b2, dbh_sq)),
                  stan::math::multiply(b3, ba_metric)),
                stan::math::multiply(b4, bal_metric)),
              stan::math::multiply(b5, cr_init)),
            stan::math::multiply(b6, ln_csi)), "assigning variable mu");
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(delta_CR_a, mu,
                         sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "crown_ratio_change_fixed_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto b0 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto b1 = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto b2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto b3 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto b4 = in__.template read<local_scalar_t__>();
      current_statement__ = 6;
      auto b5 = in__.template read<local_scalar_t__>();
      current_statement__ = 7;
      auto b6 = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto gamma =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P_trait);
      current_statement__ = 9;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> trait_effect =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_sp, DUMMY_VAR__);
      current_statement__ = 15;
      if (stan::math::logical_gt(P_trait, 0)) {
        current_statement__ = 14;
        stan::model::assign(trait_effect, stan::math::multiply(W, gamma),
          "assigning variable trait_effect");
      } else {
        current_statement__ = 13;
        stan::model::assign(trait_effect, stan::math::rep_vector(0.0, N_sp),
          "assigning variable trait_effect");
      }
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b0, 0.0, 0.25));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b1, 0.0, 0.1));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b2, 0.0, 0.01));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b3, 0.0, 0.05));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b4, 0.0, 0.05));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b5, -(0.1), 0.5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b6, 0.0, 0.5));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(gamma,
                         static_cast<double>(0), 0.5));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma,
                         static_cast<double>(0), 0.5));
        current_statement__ = 27;
        stan::math::validate_non_negative_index("mu", "N_obs", N_obs);
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_obs, DUMMY_VAR__);
        current_statement__ = 28;
        stan::model::assign(mu,
          stan::math::add(
            stan::math::add(
              stan::math::add(
                stan::math::add(
                  stan::math::add(
                    stan::math::add(
                      stan::math::add(b0,
                        stan::model::rvalue(trait_effect, "trait_effect",
                          stan::model::index_multi(sp_idx))),
                      stan::math::multiply(b1, dbh)),
                    stan::math::multiply(b2, dbh_sq)),
                  stan::math::multiply(b3, ba_metric)),
                stan::math::multiply(b4, bal_metric)),
              stan::math::multiply(b5, cr_init)),
            stan::math::multiply(b6, ln_csi)), "assigning variable mu");
        current_statement__ = 29;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(delta_CR_a, mu,
                         sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "crown_ratio_change_fixed_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto b0 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto b1 = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto b2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto b3 = in__.template read<local_scalar_t__>();
      current_statement__ = 5;
      auto b4 = in__.template read<local_scalar_t__>();
      current_statement__ = 6;
      auto b5 = in__.template read<local_scalar_t__>();
      current_statement__ = 7;
      auto b6 = in__.template read<local_scalar_t__>();
      current_statement__ = 8;
      auto gamma =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P_trait);
      current_statement__ = 9;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<double,-1,1> trait_effect =
        Eigen::Matrix<double,-1,1>::Constant(N_sp,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(b0);
      out__.write(b1);
      out__.write(b2);
      out__.write(b3);
      out__.write(b4);
      out__.write(b5);
      out__.write(b6);
      out__.write(gamma);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 15;
      if (stan::math::logical_gt(P_trait, 0)) {
        current_statement__ = 14;
        stan::model::assign(trait_effect, stan::math::multiply(W, gamma),
          "assigning variable trait_effect");
      } else {
        current_statement__ = 13;
        stan::model::assign(trait_effect, stan::math::rep_vector(0.0, N_sp),
          "assigning variable trait_effect");
      }
      if (emit_transformed_parameters__) {
        out__.write(trait_effect);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N_obs,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mu_pred =
        Eigen::Matrix<double,-1,1>::Constant(N_obs,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 12;
      stan::model::assign(mu_pred,
        stan::math::add(
          stan::math::add(
            stan::math::add(
              stan::math::add(
                stan::math::add(
                  stan::math::add(
                    stan::math::add(b0,
                      stan::model::rvalue(trait_effect, "trait_effect",
                        stan::model::index_multi(sp_idx))),
                    stan::math::multiply(b1, dbh)),
                  stan::math::multiply(b2, dbh_sq)),
                stan::math::multiply(b3, ba_metric)),
              stan::math::multiply(b4, bal_metric)),
            stan::math::multiply(b5, cr_init)),
          stan::math::multiply(b6, ln_csi)), "assigning variable mu_pred");
      current_statement__ = 17;
      for (int i = 1; i <= N_obs; ++i) {
        current_statement__ = 16;
        stan::model::assign(log_lik,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(delta_CR_a, "delta_CR_a",
              stan::model::index_uni(i)),
            stan::model::rvalue(mu_pred, "mu_pred", stan::model::index_uni(i)),
            sigma), "assigning variable log_lik", stan::model::index_uni(i));
      }
      out__.write(log_lik);
      out__.write(mu_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ b0 = DUMMY_VAR__;
      current_statement__ = 1;
      b0 = in__.read<local_scalar_t__>();
      out__.write(b0);
      local_scalar_t__ b1 = DUMMY_VAR__;
      current_statement__ = 2;
      b1 = in__.read<local_scalar_t__>();
      out__.write(b1);
      local_scalar_t__ b2 = DUMMY_VAR__;
      current_statement__ = 3;
      b2 = in__.read<local_scalar_t__>();
      out__.write(b2);
      local_scalar_t__ b3 = DUMMY_VAR__;
      current_statement__ = 4;
      b3 = in__.read<local_scalar_t__>();
      out__.write(b3);
      local_scalar_t__ b4 = DUMMY_VAR__;
      current_statement__ = 5;
      b4 = in__.read<local_scalar_t__>();
      out__.write(b4);
      local_scalar_t__ b5 = DUMMY_VAR__;
      current_statement__ = 6;
      b5 = in__.read<local_scalar_t__>();
      out__.write(b5);
      local_scalar_t__ b6 = DUMMY_VAR__;
      current_statement__ = 7;
      b6 = in__.read<local_scalar_t__>();
      out__.write(b6);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P_trait, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(gamma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(P_trait),
        "assigning variable gamma");
      out__.write(gamma);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 9;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "b0", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "b1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "b2", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "b3", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "b4", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "b5", "double",
        std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "b6", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "gamma", "double",
        std::vector<size_t>{static_cast<size_t>(P_trait)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ b0 = DUMMY_VAR__;
      current_statement__ = 1;
      b0 = context__.vals_r("b0")[(1 - 1)];
      out__.write(b0);
      local_scalar_t__ b1 = DUMMY_VAR__;
      current_statement__ = 2;
      b1 = context__.vals_r("b1")[(1 - 1)];
      out__.write(b1);
      local_scalar_t__ b2 = DUMMY_VAR__;
      current_statement__ = 3;
      b2 = context__.vals_r("b2")[(1 - 1)];
      out__.write(b2);
      local_scalar_t__ b3 = DUMMY_VAR__;
      current_statement__ = 4;
      b3 = context__.vals_r("b3")[(1 - 1)];
      out__.write(b3);
      local_scalar_t__ b4 = DUMMY_VAR__;
      current_statement__ = 5;
      b4 = context__.vals_r("b4")[(1 - 1)];
      out__.write(b4);
      local_scalar_t__ b5 = DUMMY_VAR__;
      current_statement__ = 6;
      b5 = context__.vals_r("b5")[(1 - 1)];
      out__.write(b5);
      local_scalar_t__ b6 = DUMMY_VAR__;
      current_statement__ = 7;
      b6 = context__.vals_r("b6")[(1 - 1)];
      out__.write(b6);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P_trait, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gamma_flat__;
        current_statement__ = 8;
        gamma_flat__ = context__.vals_r("gamma");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P_trait; ++sym1__) {
          stan::model::assign(gamma, gamma_flat__[(pos__ - 1)],
            "assigning variable gamma", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(gamma);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 9;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"b0", "b1", "b2", "b3", "b4", "b5",
                "b6", "gamma", "sigma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"trait_effect"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik", "mu_pred"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(P_trait)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N_sp)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N_obs)},
             std::vector<size_t>{static_cast<size_t>(N_obs)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "b0");
    param_names__.emplace_back(std::string() + "b1");
    param_names__.emplace_back(std::string() + "b2");
    param_names__.emplace_back(std::string() + "b3");
    param_names__.emplace_back(std::string() + "b4");
    param_names__.emplace_back(std::string() + "b5");
    param_names__.emplace_back(std::string() + "b6");
    for (int sym1__ = 1; sym1__ <= P_trait; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N_sp; ++sym1__) {
        param_names__.emplace_back(std::string() + "trait_effect" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu_pred" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "b0");
    param_names__.emplace_back(std::string() + "b1");
    param_names__.emplace_back(std::string() + "b2");
    param_names__.emplace_back(std::string() + "b3");
    param_names__.emplace_back(std::string() + "b4");
    param_names__.emplace_back(std::string() + "b5");
    param_names__.emplace_back(std::string() + "b6");
    for (int sym1__ = 1; sym1__ <= P_trait; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N_sp; ++sym1__) {
        param_names__.emplace_back(std::string() + "trait_effect" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "mu_pred" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"b0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b5\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b6\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P_trait) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"trait_effect\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_sp) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_obs) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_obs) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"b0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b5\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b6\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P_trait) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"trait_effect\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_sp) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_obs) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_obs) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + P_trait + 1;
    const size_t num_transformed = emit_transformed_parameters * (N_sp);
    const size_t num_gen_quantities = emit_generated_quantities * (N_obs +
      N_obs);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + P_trait + 1;
    const size_t num_transformed = emit_transformed_parameters * (N_sp);
    const size_t num_gen_quantities = emit_generated_quantities * (N_obs +
      N_obs);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = crown_ratio_change_fixed_model_namespace::crown_ratio_change_fixed_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return crown_ratio_change_fixed_model_namespace::profiles__;
}
#endif