SUBROUTINE HTGF
IMPLICIT NONE
!----------
! NE $Id$
!----------
!  THIS SUBROUTINE COMPUTES THE PREDICTED PERIODIC HEIGHT
!  INCREMENT FOR EACH CYCLE AND LOADS IT INTO THE ARRAY HTG.
!  HEIGHT INCREMENT IS PREDICTED FROM SPECIES, SITE INDEX,
!  BASAL AREA/ACRE, AND DBH.  THIS ROUTINE IS CALLED FROM
!  **TREGRO** DURING REGULAR CYCLING.  ENTRY **HTCONS**
!  IS CALLED FROM **RCON** TO LOAD SITE DEPENDENT CONSTANTS
!  THAT NEED ONLY BE RESOLVED ONCE.
!----------
!OMMONS
!
!
INCLUDE 'PRGPRM.f90'
!
!
INCLUDE 'ARRAYS.f90'
!
!
INCLUDE 'COEFFS.f90'
!
!
INCLUDE 'PLOT.f90'
!
!
INCLUDE 'CONTRL.f90'
!
!
INCLUDE 'MULTCM.f90'
!
!
INCLUDE 'PDEN.f90'
!
!
INCLUDE 'HTCAL.f90'
INCLUDE 'VARCOM.f90'
INCLUDE 'GREGMC.f90'
INCLUDE 'GOMPMC.f90'
!
!
!OMMONS
!
LOGICAL DEBUG
!
INTEGER ISPC,I1,I2,I3,I,MODE0,IVAR,ITFN
REAL SCALE,XHT,YRS,H,HTG1,HTMAX,AGET,GMOD,RELHTA,TEMHTG
INTEGER IGYR
REAL HTCUR,HGINC,CCFLV,CCHV,HGDEC
REAL OGCA(MAXTRE), MCWX, MCWA, MCWB, MCWC
INTEGER JJ, MFORM
!
!----------
!  SEE IF WE NEED TO DO SOME DEBUG.
!----------
CALL DBCHK (DEBUG,'HTGF',4,ICYC)
IF (DEBUG) WRITE(JOSTND,3)ICYC
3 FORMAT(' ENTERING SUBROUTINE HTGF CYCLE =',I5)
SCALE=FINT/YR
!----------
!  GET THE HEIGHT GROWTH MULTIPLIERS.
!----------
CALL MULTS (2,IY(ICYC),XHMULT)
! Greg HG: lazy-load coefficients/climate once (no-op unless FVS_GREGHG set)
CALL GREGLOADHG
! Greg crown recession: lazy-load coefficients once (no-op unless CROWNDRIVER or FVS_GREGCRW set)
  CALL GREGLOADCRW
IF (LGREGHG) THEN
  DO JJ=1,ITRN
    OGCA(JJ) = 0.0
    IF (DBH(JJ).LE.0.0) CYCLE
    IF (GHAVE_MCW(ISP(JJ))) THEN
      MFORM=NINT(GMCW(ISP(JJ),1)); MCWA=GMCW(ISP(JJ),2); MCWB=GMCW(ISP(JJ),3); MCWC=GMCW(ISP(JJ),4)
    ELSE
      MFORM=1; MCWA=8.0; MCWB=1.5; MCWC=0.0
    ENDIF
    IF (MFORM.EQ.2) THEN
      MCWX = MCWA * DBH(JJ)**MCWB
    ELSE
      MCWX = MCWA + MCWB*DBH(JJ) + MCWC*DBH(JJ)*DBH(JJ)
    ENDIF
    IF (MCWX.LT.0.0) MCWX = 0.0
    OGCA(JJ) = 0.7853981634*MCWX*MCWX*PROB(JJ)
  ENDDO
ENDIF
!----------
!  BEGIN SPECIES LOOP.
!----------
DO 40 ISPC=1,MAXSP
I1 = ISCT(ISPC,1)
IF (I1 .EQ. 0) GO TO 40
I2 = ISCT(ISPC,2)
XHT=XHMULT(ISPC)
!----------
!  BEGIN TREE LOOP WITHIN SPECIES LOOP
!----------
DO 30 I3 = I1,I2
I=IND1(I3)
!----------
!   CALL HTCALC TO CALCULATE AGE BASED ON CURRENT TREE HEIGHT
!----------
  MODE0= 0
  IVAR=3
  YRS=10.
  H=HT(I)
  AGET=0.
  CALL HTCALC (MODE0,IVAR,ISPC,SITEAR(ISPC),YRS,H,AGET,HTMAX, &
                  HTG1,JOSTND,DEBUG)
!----------
!   CALL HTCALC TO CALCULATE HTG BASED ON AGE GIVEN CURRENT TREE HEIGHT
!----------
MODE0=9
IVAR=3
YRS=10.
H=HT(I)
HTG1=0.
CALL HTCALC (MODE0,IVAR,ISPC,SITEAR(ISPC),YRS,H,AGET,HTMAX, &
                HTG1,JOSTND,DEBUG)
HTG(I)=HTG1
IF(DEBUG)WRITE(JOSTND,*) ' I,SI,H,AGET,HTMAX,HTG1= ', &
    I,SITEAR(ISPC),H,AGET,HTMAX,HTG1
!----------
!  GET BAL MODIFIER BORROWED FROM THE DIAMETER GROWTH EQUATIONS AND
!  ADJUST THE HEIGHT GROWTH ESTIMATE.
!  POTENTIALLY ONLY AFFECT HEIGHT GROWTH HALF AS MUCH AS DIA GROWTH
!  TEMPER THE ADJUSTMENT BY RELATIVE HEIGHT
!  ADD A RANDOM INCREMENT COMMENSURATE WITH DG RANDOM INCREMENT.
!----------
CALL BALMOD(ISPC,DBH(I),GMOD)
IF(DEBUG)WRITE(16,*)' AFTER BALMOD GMOD,HT,AVH= ',GMOD,HT(I),AVH
!      GMOD = (GMOD+1.0)/2.0
RELHTA=0.
IF(AVH .GT. 0.)RELHTA=MIN((HT(I)/AVH),1.0)
GMOD=(1.0-((1.0-GMOD)*(1.0-RELHTA)))*0.8
HTG(I)=HTG(I)*(1.0+OLDRN(I))*GMOD
!
IF(DEBUG)WRITE(16,*)' I,HTG,RELHTA,GMOD,OLDRN= ', &
   I,HTG(I),RELHTA,GMOD,OLDRN(I)
!
IF(HTG(I) .LT. 0.1)HTG(I)=0.1
HTG(I)=SCALE*XHT*HTG(I)*EXP(HTCON(ISPC))
IF(DEBUG) WRITE(JOSTND,*) 'I= ',I,'  SCALE= ',SCALE,'  XHT= ', &
     XHT, '  HTG(I)= ',HTG(I),' HTCON= ',HTCON(ISPC)
TEMHTG=HTG(I)
! --- Greg HG substitution (behind FVS_GREGHG): override native HTG for covered species ---
IF (LGREGHG .AND. GHAVE_HG(ISPC)) THEN
  CCHV = CCHT(I)                       ! crown closure at tip from gompit GOMPCCH (0 if gompit off)
  CCFLV = 0.0
  DO JJ = 1, ITRN
    IF (DBH(JJ) .GT. DBH(I)) CCFLV = CCFLV + OGCA(JJ)
  END DO
  CCFLV = 100.0/43560.0 * CCFLV        ! Greg ccfl: CCF of larger trees from MCW
  HTCUR = HT(I)
  DO IGYR = 1, 10
    CALL GREGHGV(ISPC, HTCUR, FLOAT(ICR(I))/100.0, CCFLV, CCHV, HGINC)
    HTCUR = HTCUR + HGINC
  END DO
  HGDEC = HTCUR - HT(I)                ! 10-yr Greg height increment
  HTG(I) = SCALE * XHT * HGDEC         ! scale to cycle, keep user multiplier; bypass native GMOD/HTCON
  IF (HTG(I) .LT. 0.1) HTG(I) = 0.1
  TEMHTG = HTG(I)
ENDIF
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
!----------
IF((HT(I)+HTG(I)).GT.SIZCAP(ISPC,4))THEN
  HTG(I)=SIZCAP(ISPC,4)-HT(I)
  IF(HTG(I) .LT. 0.1) HTG(I)=0.1
ENDIF
!
IF(.NOT.LTRIP) GO TO 30
ITFN=ITRN+2*I-1
HTG(ITFN)=TEMHTG
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
!----------
IF((HT(ITFN)+HTG(ITFN)).GT.SIZCAP(ISPC,4))THEN
  HTG(ITFN)=SIZCAP(ISPC,4)-HT(ITFN)
  IF(HTG(ITFN) .LT. 0.1) HTG(ITFN)=0.1
ENDIF
!
HTG(ITFN+1)=TEMHTG
!----------
! CHECK FOR SIZE CAP COMPLIANCE.
!----------
IF((HT(ITFN+1)+HTG(ITFN+1)).GT.SIZCAP(ISPC,4))THEN
  HTG(ITFN+1)=SIZCAP(ISPC,4)-HT(ITFN+1)
  IF(HTG(ITFN+1) .LT. 0.1) HTG(ITFN+1)=0.1
ENDIF
!
IF (DEBUG) WRITE(JOSTND,9001) HTG(ITFN),HTG(ITFN+1)
9001 FORMAT( ' UPPER HTG =',F8.4,'LOWER HTG =',F8.4)
!----------
!  END OF TREE LOOP
!----------
30 CONTINUE
!----------
!  END OF SPECIES LOOP
!----------
40 CONTINUE
RETURN
!
ENTRY HTCONS
!----------
!  ENTRY POINT FOR LOADING HEIGHT INCREMENT MODEL COEFFICIENTS THAT
!  ARE SITE DEPENDENT AND REQUIRE ONE-TIME RESOLUTION.  HGHC
!  CONTAINS HABITAT TYPE INTERCEPTS, HGLDD CONTAINS HABITAT DEPENDENT
!  COEFFICIENTS FOR THE DIAMETER INCREMENT TERM,HGH2 CONTAINS
!  HABITAT DEPENDENT COEFFICIENTS FOR THE HEIGHT-SQUARED TERM, AND
!  HGHC CONTAINS SPECIES DEPENDENT INTERCEPTS.  HABITAT TYPE IS
!  INDEXED BY ITYPE (SEE /PLOT/ COMMON AREA).
!----------
!----------
!  LOAD OVERALL INTERCEPT FOR EACH SPECIES
!----------
DO 60 ISPC= 1,MAXSP
HTCON(ISPC)= 0.0
IF(LHCOR2 .AND. HCOR2(ISPC).GT.0.0) HTCON(ISPC)= &
       HTCON(ISPC)+ALOG(HCOR2(ISPC))
60 CONTINUE
RETURN
END
